version: '3'
services:
  app:
    image: noteisenheim/frog-website:v1
    volumes:
      - ./templates/:/app/templates/
      - ./static:/app/static
    ports:
      - "5000:5000"

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - app
    ports:
      - "80:80"